campionato_costruttori <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/constructor_results.csv",header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
constructors_standings <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/constructor_standings.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
costruttori <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/constructors.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
drivers_standings <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/driver_standings.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
drivers <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/drivers.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
lap_times <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/lap_times.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
pitstops <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/pit_stops.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
qualifiche <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/qualifying.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
races <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/races.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
risultati <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/results.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
stagioni <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/seasons.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
status <- read.table("C:/Users/david/Desktop/Università/Scienza dei dati/f1db_csv/status.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
